In [1]:
import os
import re

import numpy as np
import pandas as pd

In [2]:
data_dir = '/home/hariub/data/HAR/raw/Daphnet/dataset'

In [6]:
def preprocess_daphnet(data_dir):
    data_files = sorted(os.listdir(data_dir))
    cols = ['Time', 'Ankle_acc_x', 'Ankle_acc_y', 'Ankle_acc_z', 'Thigh_acc_x', 'Thigh_acc_y', 'Thigh_acc_z', 'Trunk_acc_x', 'Trunk_acc_y', 'Trunk_acc_z', 'Label']
    
    complete_df = pd.DataFrame()
    
    for d_file in data_files:
        user, run = re.findall(r'\d+', d_file)
        
        data_arr = np.loadtxt(os.path.join(data_dir, d_file), delimiter=' ')
        _df = pd.DataFrame(data=data_arr, columns=cols)
        _df['Subject'] = int(user)
        _df['Run'] = int(run)
        
        complete_df = pd.concat([complete_df, _df], ignore_index=True)
        
    complete_df = complete_df.sort_values(by=['Subject', 'Run'], ignore_index=True)
    complete_df.to_csv('/home/hariub/data/HAR/processed/clean_daphnet_data.csv', index=False)
    
    return complete_df

In [7]:
preprocess_daphnet(data_dir)

,Time,Ankle_acc_x,Ankle_acc_y,Ankle_acc_z,Thigh_acc_x,Thigh_acc_y,Thigh_acc_z,Trunk_acc_x,Trunk_acc_y,Trunk_acc_z,Label,Subject,Run
0,15.0,70.0,39.0,-970.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
1,31.0,70.0,39.0,-970.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
2,46.0,60.0,49.0,-960.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
3,62.0,60.0,49.0,-960.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
4,78.0,50.0,39.0,-960.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1917882,3020296.0,-131.0,107.0,-960.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10,1
1917883,3020312.0,-121.0,127.0,-970.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10,1
1917884,3020328.0,-141.0,117.0,-960.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10,1
1917885,3020343.0,-131.0,127.0,-980.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10,1
1917886,3020359.0,-141.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10,1